# Docker compose sample file

version: '3'
services:
  botator:
    image: botator/botator:latest
    container_name: botator
    restart: always
    volumes:
      - ./database:/Botator/database
    environment:
      - PERSPECTIVE_API_KEY=your_api_key
      - WEBHOOK_URL=https://yourdomain.com/botator
      - DISCORD_TOKEN=your_token