# Docker compose sample file

version: '3'
services:
  botator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./database:/Botator/database
    env_file:
      - .env